CREATE TABLE AppLog(
USER_ID VARCHAR(20)    NOT NULL,
DATED   varchar(50)    NOT NULL,
LOGGER  VARCHAR(50)    NOT NULL,
LEVEL   VARCHAR(10)    NOT NULL,
MESSAGE VARCHAR(1000)  NOT NULL
)ENGINE=InnoDB CHARSET=utf8;